#!/bin/bash

#
# Usage: sudo ./main 2>&1 | tee main.log
#

TIMEOUT=10 # seconds to wait before killing an unresponsive connection
WAKEUP=5 # seconds to wait after restarting tor
DATA_DIR=data/torify # path to store timestamped results

function main() {
	log_info "press ctrl+c to quit"
	mkdir -p $DATA_DIR
	while :; do
		restart_tor && sleep $WAKEUP && log_info "restarted tor"
		if [[ -z $(torify curl ifconfig.me 2>/dev/null) ]]; then 
			log_error "bad circuit"
		fi

		torify python3 rttct.py \
			-i scthash.json \
			-o "$DATA_DIR/$(date +"%Y%m%d_%H%M%S").json" \
			-t $TIMEOUT
	done
}

function restart_tor {
	service tor stop
	rm /var/lib/tor/state
	service tor start
}

function log_info() {
	echo "[Info] $@" >&2
}

function log_error() {
	echo "[Error] $@" >&2
}

main
