#!/bin/bash

#
# domain_list
# Outputs the k top-most domain names from Alexa top-1M with https:// prepended.
# 

if [ $# -ne 2 ] || ([[ $1 -lt 0 ]] || [[ $1 -gt 1000000 ]]); then
	echo "Usage: ./domain_list <k> <dst dir>, where k in [1,1M]" 1>&2
	exit 1
fi

if [[ ! -f $2/top-1m.csv ]]; then
	echo "[Info] downloading alexa top-1m" 1>&2
	wget http://s3.amazonaws.com/alexa-static/top-1m.csv.zip &&
		unzip -d $2 top-1m.csv.zip
	rm -f top-1m.csv.zip
fi

if [[ ! -f $2/top-1m.csv ]]; then
	echo "[Error] failed to download and unzip alexa top-1m" 1>&2
	exit 1
fi

echo $(\
	cat $2/top-1m.csv |\
	cut -d, -f2 |\
	awk -v OFS='' '{print "https://", $0}' |\
	head -n$1 |\
	xargs\
)
