#!/bin/bash

#
# sct_probe
# <docdoc>
#

sctcheck=~/go/src/github.com/google/certificate-transparency-go/ctutil/sctcheck/sctcheck
serializer=~/go/src/github.com/google/certificate-transparency-go/serialization.go
ddir=../data
k=100

mkdir -p $ddir
[[ ! -x $sctcheck ]] &&
	echo "[Error] scthcheck is not executable" 1>&2 &&
	exit 1
[[ ! -f $serializer ]] &&
	echo "[Error] invalid path to serializer.go" 1>&2 &&
	exit 1
[[ ! "$(cat $serializer)" =~ "b64__leaf-hash" ]] &&
	echo "[Error] no leaf hash output in serializer.go, see README.md" 1>&2 &&
	exit 1

echo "[Info] custom ct setup ok" 1>&2
echo "[Info] collecting scts for k=$k in $ddir"
$sctcheck --logtostderr $(./domain_list $k $ddir) 2>&1 |\
	awk '(/Check embedded SCT/ && !/included at/) || /b64__leaf-hash/ { print; }' |\
	tee $ddir/output.log
