#!/bin/bash

#
# Usage: ./client
# Usage: env CTOR_SUBMIT_BYTES=5012 CTOR_SERVER_IP=127.0.0.1 ./client
#

[ -z $CTOR_SUBMIT_BYTES ] && CTOR_SUBMIT_BYTES=8
[ -z $CTOR_SERVER_IP ] && CTOR_SERVER_IP=localhost
[ -z $CTOR_SERVER_PORT ] && CTOR_SERVER_PORT=8080

curl -X POST \
	-H "Content-Type: text/plain" \
	--data $(python3 -c "print('a'*$CTOR_SUBMIT_BYTES)") \
	$CTOR_SERVER_IP:$CTOR_SERVER_PORT
